version: '2'
services:
  server:
    build: ./server
    container_name: server
    expose:
      - '5000'
    ports:
      - '5000:5000'
    volumes:
      - './server/:/usr/src/app/server'
  client:
    build: ./client
    container_name: client
    expose:
      - '3000'
    ports:
      - '80:3000'
    volumes:
      - './client/:/usr/src/app/client'
    links:
      - server
